all: structest structest1 structest2 structest3 structest4
structest: structest.cpp
	cc -Wall -o structest structest.cpp -lm
structest1: structest1.cpp
	cc -Wall -o structest1 structest1.cpp -lm
structest2: structest2.cpp
	cc -Wall -o structest2 structest2.cpp -lm
structest3: structest3.cpp
	cc -Wall -o structest3 structest3.cpp -lm
structest4: structest4.cpp
	cc -Wall -o structest4 structest4.cpp -lm
clean:
	rm -f structest structest1 structest2 structest3 structest4
	rm -f cmultest.dat cmultest_r*.dat structest2.log cmultest.ps
